services:
  web:
    build: .
    ports:
      - "80:80"
    command: python3 backend/run.py
    volumes:
      - .:/data
    depends_on:
      - db
      - redis
    networks:
      - app-network

  db:
    image: postgres:13

    environment:
      POSTGRES_USER: myuser01
      POSTGRES_DB: api_db
      POSTGRES_PASSWORD: 1234

    ports:
      - "5432:5432"

    volumes:
      - db-data:/var/lib/postgresql/data

    networks:
      - app-network

  redis:
    image: redis/redis-stack

    ports:
     - "6379:6379"

    networks:
     - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge