services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      DB_URL: ${DB_URL}
      SECRET_KEY: ${SECRET_KEY}
      REDIS_URL: ${REDIS_URL}
    command: bash -c "cd backend && alembic upgrade head && cd .. && uvicorn backend.main:app --host 0.0.0.0 --port 80"
    volumes:
      - .:/data
    depends_on:
      - db
      - redis
    networks:
      - app-network

  db:
    image: postgres:13

    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: testdb

    ports:
      - "5432:5432"

    volumes:
      - db-data:/var/lib/postgresql/data

    networks:
      - app-network

  redis:
    image: redis/redis-stack

    ports:
     - "6379:6379"

    networks:
     - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge